### ISSUE TITLE
Fake X on 0 extrapolation! WTF?

### ISSUE THREAD

**Issue by spr1907** [haxball/haxball-issues#1011]
https://www.youtube.com/watch?v=aJcRzZnQzKM

Dear Basro, just watch this. I am playing with 0 extrapolation and I still see this fake x thing? How is this possible? I am not supposed to see this right? But why is it happening then?

We are waiting for hotfix. People is abusing this bug and it should be fixed as soon as possible.

**Comment by hax-ops** [comment]
If you want more proof, I can give you more evidence of this. but don't ignore this. I don't want to see fake x (pixel fake) when I play with no extrapolation at all.

**Comment by spr1907** [comment]
@basro @basaringaron

**Comment by basro** [comment]
Not sure why you think this would be exclusive to extrapolation. This is a prediction artifact that happens when the game gets the prediction wrong and has to roll back the kick.

Unless there's something that I'm missing this is not a bug and has been like this from the very first version of HaxBall.
