### ISSUE TITLE
setTeamColors Chat 

### ISSUE THREAD

**Issue by bananaGrandma** [haxball/haxball-issues#1035]
I'm trying to make it so if you say something like !libertiesredhome it will change the team colors. But for some reason, when I add another command with different colors such as, !mountainsredhome, it doesn't work and crashes the server. 
Here is the code. 
```
room.onPlayerChat = function(player, message) {
if (player && message == "!colors") {
		room.sendChat("!samurais, !liberties, !mountains, !ice")
		return true;
	}
	if (player && message == "!liberties") {
		room.sendChat("Red: !libertiesred or Blue: !libertiesblue")
		return true;
	}
	if (player && message == "!libertiesred") {
		room.sendChat("Home: !libertiesredhome or Away: !libertiesredaway")
		return true;
	}
	if (player && message == "!libertiesredhome") {
		room.setTeamColors(1, 90, 0xFFFFFF [0xFF9914, 0xFCBB08]);
		return true;
	}
	if (player && message == "!libertiesredaway") {
		room.setTeamColors(1, 20, 0xFFFFFF, [0x3B3B3B, 0xFFFA61]);
		return true;
	}
	if (player && message == "!libertiesblue") {
		room.sendChat("Home: !libertiesbluehome or Away: !libertiesblueaway")
		return true;
	}
	if (player && message == "!libertiesbluehome") {
		room.setTeamColors(2, 60, 0xFFFFFF, [0x0CC782, 0x363636]);
		return true;
	}
	if (player && message == "!libertiesblueaway") {
		room.setTeamColors(2, 90, 0xFFFFFF [0xFF9914, 0xFCBB08]);
		return true;
	}
	if (player && message == "!mountains") {
		room.sendChat("Red: !mountainsred or Blue: !mountainsblue")
		return true;
	}
	if (player && message == "!mountainsred") {
		room.sendChat("Home: !mountainsredhome or Away: !mountainsredaway")
		return true;
	}
	if (player && message == "!mountainsredhome") {
		room.setTeamColors(1, 90, 0xFFFFFF [0xFF9914, 0xFCBB08]);
		return true;
	}
}
```

Now, the commands with !liberties with it works, but not the ones with !mountains
Thanks!

**Comment by AnddyAnddy** [comment]
It looks like you forgot some  ` , ` in room.setTeamColors (right after the 0xFFFFFF)

Also
- since you requiere ALL commands to be player not null, you can do at the top
```
if (player) {
all the if
```

- since the commands are strictly disjoints (you can't have 2 commands in the same message) you can use `else if` instead of `if`, it works in the same way, you just add the else keyword before the if from the second one (it'll prevent the exec to run all the if when he already found an answer, see my next point) 

- since the onPlayerChat has a modification on his behaviour only if you return false, the return true is not needed anymore if you apply my point above (less lines) 

- more advanced: you can use an object to store all the !commands like that
```js
let commands = {
    "command_1": function_applying_command1, 
    "command_2": function_applying_command2, 
    "command_3": function_applying_command3, 
    "command_n": function_applying_commandn
}
```
And have your on Player Chat like that
```js
room OnPlayerChat = function(player, message) {
    if (player && commands.hasOwnProperty(message){
    return commands[message]();
} 
```


(all this post about missing some , lol)

**Comment by bananaGrandma** [comment]
I guess I was really tired when I was coding that I forgot to put commas lol. And thanks for the other tips as well!
