### ISSUE TITLE
Server not getting inputs with perfect connection

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#1045]
Hello basro,

I'm writing this issue since me and another player experience the same issue : 
We have a good laptop, however we both experience problems with inputs. Sometimes, the player continues in the same direction for some time, just like a freeze, however the connection has nothing to do with this.

To showcase this issue better, i'm adding some videos and pictures :
- The ping graph of the player
![image](https://user-images.githubusercontent.com/39807740/78511092-50a6d080-779a-11ea-8c37-cd4802ed8c49.png)
- The (huge) problem in action
https://i.gyazo.com/601ce28ff2906ca04ee922f207aaaf0e.mp4
I asked the player to keep doing roulette, and the problem that I'm currently describing made it so he completely deviated from his objective.

As of now, he cannot play the game because this bug kills the fun one can have (imagine having freezes that hard every 15s).
Fortunately for me, I have a PC that works perfectly fine, but he only has his laptop, so we really need guidance on this so he can enjoy HaxBall.

Also, he tested every browser, and encountered the same issue everytime, it doesn't seem to matter.
If you have any questions or requests let me know i'll answer quickly.

Thanks, and have a great day.

**Comment by basro** [comment]
Please check if this also happens when you are the room host. (I mean that you should check if player who hosts can get his keys stuck like this or not)

And also please host a room and join it from a new browser window, see if you can get the keys stuck like that in that window.

The symptoms you show in the video are consistent with packet loss, which the ping graph is not very good at detecting. You should measure your connection's packet loss with an external tool if possible.

**Comment by basro** [comment]
If his laptop has an ethernet adapter, try connecting the laptop to the internet using that instead of Wifi.

**Comment by Wazarr94** [comment]
Ok I'll see with him and send an update as soon as possible, thanks !

**Comment by Wazarr94** [comment]
Given he has no issue in a self hosted room, you're probably right.
At the moment he doesn't have an ethernet cable, but I'm pretty sure it will fix his problem.

Closing, I'll reopen if this doesn't cut it. Thanks
