### ISSUE TITLE
Is there any specification of hbr2?

### ISSUE THREAD

**Issue by dapucita** [haxball/haxball-issues#1171]
I know already that the header is [HBR2][version][length]
![asad](https://user-images.githubusercontent.com/45658904/97808333-ae0bed00-1ca9-11eb-8a39-37bac782fc2b.PNG)

but I want to know the left part of replay file.
(maybe zlib compressed..)

Can I ask you some document or any hints about this?

**Comment by basro** [comment]
The rest of the file is not documented because it's not a stable api, it can change drastically every time I make updates.
Not to mention that the contents of a replay file are not very useful since they only store input, to know anything about the game state in the replay the game logic needs to be re-simulated exactly.

I might some day implement a tool that replays the game and converts it into a list of positions and events for each frame.

**Comment by dapucita** [comment]
thx your comment, gracias.
