### ISSUE TITLE
Steam version of Haxball

### ISSUE THREAD

**Issue by hypehaxx** [haxball/haxball-issues#125]
I think the most popular feature here will be creating a separate client for haxball with registration, national championship system, international tournaments, forums, free agents etc.. Haxball community needs the one centralized resource to play such tournaments as Champions League or Nations Cup. It would be great to have access to all statistics of the past tournaments in one place. If haxball get into Steam with such kind of features - this game will become in 9343489 times popular then now.

**Comment by haxballer** [comment]
Have to admit that Haxball just needs it to survive. First of all, the downloadable version is something that many people dream of, because well programmed in the end, it could forever fade the problem of fps and any bugs, so playing on older pc would be no trouble, as is in games like Tibia, Haxball It's not something that is graphically complicated, but browsers plays it's bad. Popularity is also a problem, as you can see Basro hesitates, or don't know how to realize, pity.

**Comment by basro** [comment]
I have no current plans to make a steam version.

**Comment by haxballer** [comment]
@basro I hope you will ever develop HaxBall to the full version, it doesn't necessarily have to be on steam. I would like the Hax players to get more serious, and not just through the prism of the browser. :P
