### ISSUE TITLE
Adjusting The Color İn The Throw İn

### ISSUE THREAD

**Issue by finXed** [haxball/haxball-issues#1274]
Hello!

As I mentioned in the title, I want to adjust the shape of the jersey. I want the color of the ball to be the color of the team that will use the crown shot. How can I do this?

For example: the red team's jersey color is orange. The color of the ball will automatically be orange when the ball hits the crown shot.

In my current codes, there is the following code about the ball color: setBallColor(lastCall == 1 ? 0xFF0000:0x0000FF);

Thanks.

**Comment by finXed** [comment]
.

**Comment by thenorthstar** [comment]
> Hello!
> 
> As I mentioned in the title, I want to adjust the shape of the jersey. I want the color of the ball to be the color of the team that will use the crown shot. How can I do this?
> 
> For example: the red team's jersey color is orange. The color of the ball will automatically be orange when the ball hits the crown shot.
> 
> In my current codes, there is the following code about the ball color: setBallColor(lastCall == 1 ? 0xFF0000:0x0000FF);
> 
> Thanks.

@finXed 

Yeah. I think most of the people who plays haxball have these scripts. There is function named as **checkBallPosition()** in somewhere in these scripts. You can adjust the ball color there.

A simple suggestion: Learn some basic English. Because it's obvious that you're using a translator. I'm saying this because using of translator makes one's sentences harder or to be understood. Trust me.
