### ISSUE TITLE
Some maps won't load/save properly in the Stadium Editor/haxpuck

### ISSUE THREAD

**Issue by kingjasko** [haxball/haxball-issues#1288]
So, I tried both stadium editors (https://haxball-stadium-editor.github.io/ and https://haxball.github.io/haxpuck/hbedit/), but often times some maps don't want to properly load, as it's impossible to press the "save" button after uploading the map. On top of that, when that happens, it's also impossible to edit the map visually through the editor.

Normal behaviour would be uploading a map or copy pasting it's code, pressing the "save" button and the map loads visually normally and you're then able to edit it visually using the editor, but yeah, that's not the case with this bug.

I'd like to know what causes it and if there's a workaround.

**Comment by ChasmSolacer** [comment]
When I had this problem before, it was caused by a disc not having specified the pos property. Haxball defaults it to [0,0] but HBSE seems to bluescreen because of it.
Try to search for "discs" word in your hbs file and you could find something similar to this:
```js
"discs":[{"radius":20,"cGroup":["ball","kick","score"]}, (other discs...)
```
Notice that it's missing the pos, so you need to add **"pos":[0,0]** like this:
```js
"discs":[{"pos":[0,0],"radius":20,"cGroup":["ball","kick","score"]}, (other discs...)
```

**Comment by kingjasko** [comment]
can confirm that this was the issue, thanks!
