### ISSUE TITLE
About a Bug on Unstorable Maps

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1383]
Hello @basro. As most of HaxBall players know, we couldn't store a map which has **canBeStored:false**. But apparently, it's not true. A player from Turkey stored unstorable maps when opened and uploaded them to HaxMaps.

![1](https://user-images.githubusercontent.com/68077608/125170707-de047c00-e1b8-11eb-9d90-b445d66735f9.PNG)

For example, all these maps were unstorable in their original (I know bcs. of some of them are my own work) but storable in HaxMaps versions now.

Through my conversations, I have learnt that he has made it in another servers' rooms and could do it by some extensions and coding. We would really pleased if you can solve this bug. Thanks from right now!

https://dosya.co/u5p4z47n8x09/Screen_recording_2021-07-10_18.26.41.webm.html

20:23 Turkish time dit: He's storing an unstorable map. Please watch this.

**Comment by saviola777** [comment]
I don't think this can be "solved", because it's all happening on the client. Basro has built a check into the Haxball client which does not store a map if `canBeStored` is `false`. But the client is JavaScript and pretty easy to manipulate, so anyone can remove this check and store the map.

**Comment by basro** [comment]
It is as saviola said, this is unavoidable unfortunately.

**Comment by thenorthstar** [comment]
@saviola777 @basro Frankly it's sad but OK. Thank you for interests. ☺️

**Comment by namajunas** [comment]
I'll be posting a map for a while until this issue is resolved. this is a serious problem! @basro

**Comment by BotcuHasan** [comment]
I found this first and i give it to one of my friend(old) and he is the one who stealed those maps and shared on haxmaps i think the person behind this game could make it little harder instead of doing simple check like you could create some tool that map makers upload their maps with objects(vertex etc) and its converting it to gif file or some other types you could achieve same look and map makers upload that generated file instead of pure map file idk if its possible just made it up and if someone else dont do similar thing

I wont try it again obviously i think you should patch this whatever why possible i hope no one else exploit it when you fix it. because i wont. i just want from you to make it as hard as you can like no one who is not experienced could find a bypass. I will not answer anything come after this post good luck

**Comment by SemsekMeke** [comment]
You can remove the "store" command. We are efforts on maps. It will be better for all of us.

**Comment by r00t-ux** [comment]
@basro You can do it as he says. Everyone put their effort on it but someone comes and steals the maps. Don't let this thievery and do your duty. -Shingeki

**Comment by poinkler** [comment]
@basro Can you completely remove the / store command? It would be better if it was just downloaded from Haxmaps to get the map.

**Comment by Vhagar26** [comment]
@basro Hi, I am one of the famous map maker in this game. I can say this about this subject; Sometimes it takes hours to make a single map. By the way, 6 years of experience + hours. That's why we make some maps only for our server and our friends. But with these thieves it doesn't matter. As a suggestion you can **remove the store command.** I will not continue the making map until this issue is resolved. I also mentioned this in the description of my haxmaps account. https://haxmaps.com/author/2408

**Comment by nediunlann** [comment]
@basro Actually, I'm not very knowledgeable about coding. I just believe you can do something about it. my friends put in a lot of effort and I don't want their work stolen.

**Comment by vvaln** [comment]
@basro Hey, have a nice day mate. This little cute game always seemed like a kid back yard to me. The low population of funny kids were having good time here. Me myself and my friends here all of us want you to recognize our little back yard which you left for eternity ! Honestly i was surprised about that HTML5 update :D . Cuz as I said the game was abandoned ! I guess haxball exists for the ones who want to hang out with his own decisions, in freedom and with friends. This 2d game satisfies all of this important worths that cost too much for the other games.

I'm a mapmaker who edits every map to learn something. I'm a mapmaker who tries to find the right parameters of a futsal ball !
If I dont want to make a futsal ball, then who is gonna play futsal maps? I'm a mapmaker who tries to make new fun maps, if i dont try new things then who is gonna burn down the fun rooms ! Do you know even if there are so much maps, too less of them are precious and there are just a few professional mapmakers?

Right now, we need help. If you didnt own the game, then we wouldnt get mad at you, but we did. If I talk for  myself its so annoying that I struggle to make new things with my mapmaker friends and someone gets it just in 4-5 seconds, then shares it on haxmaps, comes to my room again, and sends the link to me ! He called me thief on my map which he shared like he made the map. Thank God all of my friends know what can i do on a map, right? 

Or should we thank you for your ' duty ' ? Come on, get your ass and do what you gotta do ! You do know what you gotta do..

Or wait for ice bear to eat you up ! ( this was serious by the way) 

edit : it would be disrespectful for all to do not what needs to be done !

**Comment by Cigga** [comment]
@basro People spend their _**time**_ making these maps. It would be great if there was a precaution against the theft of maps. If you can't take action you can remove the **_store command_**

**Comment by intehar** [comment]
@basro You can remove the store command, because people who make maps spend serious time

**Comment by Mons321** [comment]
@basro People spend their time making these maps. It would be great if there was a precaution against the theft of maps.

**Comment by sisyy** [comment]
Map makers spend a lot of time making these maps. As long as this bug in haxball is gone, the efforts of many makers will be wasted. Unless this bug is fixed, haxball is nothing more than a labor thief's nest. @basro

**Comment by tratoxic99** [comment]
@basro have a nice day, We would be glad if you are interested in this subject.

**Comment by HaxballMan** [comment]
@basro Hello, I am one of the old map maker in this game. Making maps is a long and arduous task and sometimes we prefer to give the maps we make to the people we trust or keep them for ourselves rather than making them public. But the /store command sometimes causes the things we want to go wrong. I think it would be pretty nice if an important precaution could be taken for this command. Have a nice day.

**Comment by Francoooooo** [comment]
Hi @basro , I will be glad if you solve the map stealing problem on haxball.

**Comment by thenorthstar** [comment]
I think that he won't respond anything. Apparently he doesn't give a fuck to his own game. Anyway, there's no problem for me as I made my maps as nothing when stealed by someone. At least you can try to do this if basro doesn't make smth anymore (that is, to make your maps working by script). For example: https://haxmaps.com/map/12467

**Comment by Lioss123** [comment]
I've been a Haxball Player for 4 Years. I want you to fix the store problem @basro

**Comment by Kronos-41** [comment]
Can you remove the /store command. İf you remove it, haxball will get even better

**Comment by WappYYy** [comment]
I think you should remove the /store command in the game. If you remove it, it will be better for the development of the game

**Comment by xlNonamelx** [comment]
hi @basro, the store command needs to be removed, the maps are stolen because of the store command. We would be very happy if you fix this bug.

**Comment by xRoos3velt** [comment]
@thenorthstar Can u add me on Discord. I need to ask sth important. xRoos3velt#3441
Thx
