### ISSUE TITLE
team ranking

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1430]
How can I add a ranking with the team and the people who were on it who had the most victories in the room?

**Comment by genals** [comment]
Since nobody wanted to help you yet, i will give you a little hint on how to do it:

1. You have to remember which players were on which team.
2. You have to look at [onTeamVictory](https://github.com/haxball/haxball-issues/wiki/Headless-Host#onteamvictory) to see which team has scored more goals (this team won).
3. For a ranking you need a list that is sorted according to the number of wins. The list contains entries for each victorious team, for example names of the players and the amount of victories.
If they are the same players, you increase the amount of victories in that entry. If this constellation of players is not in the list you create a new entry.
4. Done.

I hope this approach will help you.
