### ISSUE TITLE
Limiting joining if ping is too high

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1606]
Hi guys, 
How to kick players with too high ping?

**Comment by thenorthstar** [comment]
> Hi guys, How to kick players with too high ping?

@byoxygen In order to do this, you have to be able to read and edit the obfuscated code of the headless API. Also, kicking players on join by ping is may result in kicking of more than a half of players because of players may have high amount of ping on join. After learning how to read and edit the API, you can easily make your code as follows:

```js
var playerList = {};
var pingLimit = 100;
var enoughTime = 5000;

function checkPlayerPings(){
    var players = room.getPlayerList().filter(p => checkPlayerRoomTime(p) > enoughTime && p.ping > pingLimit);

    players.forEach(p => {
	room.kickPlayer(p.id,`Your ping must be less than ${pingLimit}`,false);
    });
}

function checkPlayerRoomTime(player){ //This is not the total online time, just for checking the players who are in the room for more than a certain time
    return Date.now() - playerList[player.name].jointime;
}

room.onPlayerJoin = function(player){
    if(playerList[player.name] == undefined){
	playerList[player.name] = {name: player.name, auth: player.auth, conn: player.conn, jointime: Date.now()};
    }
    else{
	playerList[player.name].jointime = Date.now();
    }
}
```
Output: 
![image](https://user-images.githubusercontent.com/68077608/161138242-857849db-7024-4dfc-9af9-5fcf17ac0bcb.png)

Note: I have changed the **pingLimit** to perform the output. Also, API side is your homework as I wrote above. Good luck!

**Comment by byoxygen** [comment]
@thenorthstar I dont have any idea about the API. Can you give me an example?

**Comment by thenorthstar** [comment]
> @thenorthstar I dont have any idea about the API. Can you give me an example?

@byoxygen Don't you even have any idea about the API? Don't you really know this one?

![image](https://user-images.githubusercontent.com/68077608/161148109-5d2bea15-bd84-4c0b-ada9-071e8d5b9072.png)

**Comment by byoxygen** [comment]
@thenorthstar So, I don't know how to add ping checker to API. I've also tried editing recently but couldn't identify exactly my file. 
I just want to solve the ping issue. Can you share your changed version with me from DM or here?

**Comment by thenorthstar** [comment]
> @thenorthstar So, I don't know how to add ping checker to API. I've also tried editing recently but couldn't identify exactly my file. I just want to solve the ping issue. Can you share your changed version with me from DM or here?

@byoxygen No, I won't share it. It's your homework. Good luck.
