### ISSUE TITLE
Documentation on .hbr2 files

### ISSUE THREAD

**Issue by luisgurmendezMLabs** [haxball/haxball-issues#1629]
I want to be able to read a .hbr2 file and know player positions in every tick etc. We already have a similar thing for the replay header here: https://github.com/haxball/haxball-issues/wiki/Linking-to-replay-files#hbr2-binary-header It would be nice to have it also for the replay's body. I don't think this would expose any of the game logic or code, nor will be helpful for reverse engineer the game.js file. It's just simply so that we can do some analysis for the players and the game itself, is there a reason why this isn't documented?

**Comment by hbenormous** [comment]
> I want to be able to read a .hbr2 file and know player positions in every tick etc. We already have a similar thing for the replay header here: https://github.com/haxball/haxball-issues/wiki/Linking-to-replay-files#hbr2-binary-header It would be nice to have it also for the replay's body. I don't think this would expose any of the game logic or code, nor will be helpful for reverse engineer the game.js file. It's just simply so that we can do some analysis for the players and the game itself, is there a reason why this isn't documented?

É possível alterar este site é um ótimo exemplo
https://haxball-replay-analyzer.github.io/

**Comment by luisgurmendezMLabs** [comment]
@hbenormous I've seen that! Or a prev version of it. it's sick! Really great job, although it seems to be super hacky

**Comment by luisgurmendezMLabs** [comment]
@basro any thoughts?

**Comment by basro** [comment]
The replays only store the player inputs. The position of players and everything else is obtained by running the same simulation as the game through determinism (the reason why using the seek bar in the replay is not instant). So you'd not be able to do what you intend even if it was documented.

Also, the reason why it's not documented is because it's not stable, it's a format which I allow myself to change when I make updates for the game. Making any tool that reads that data has the risk of becoming obsolete when an update happens.

**Comment by luisgurmendezMLabs** [comment]
@basro I just saw this! thanks for the explanation!. I always thought it did store everything and was super curious to know how this was achieved with so little space.
