### ISSUE TITLE
bug after update

### ISSUE THREAD

**Issue by BartoszSzubski** [haxball/haxball-issues#1827]
![problem](https://user-images.githubusercontent.com/66081470/234137792-3864e76d-d21f-4aec-8541-3471baeb936e.PNG)

Hello i have a new problem after last update. When I use Tab to write something, few seconds after it, lobby pops up covering the pitch which needs to be closed with the Escape. It happens every time now, so its unplayable for me at the moment. I have been using Google Chrome to play Haxball for many years and I have never experienced such a problem. Any tips on how to fix it or maybe others are having this issue as well?

**Comment by basro** [comment]
I'm able to reproduce this, I'll fix it soon.

This happens because after pressing tab again (trying to defocus the chat input) the menu button is getting focused. If you want a workaround while you wait you can try kicking the ball with a key other than spacebar.

This bug existed before but it was the send button that was getting focused, which did nothing visible when actioned with the spacebar.

**Comment by BartoszSzubski** [comment]
Ah ok, I get it, I've played using spacebar all my life so I guess I gotta wait :< Meanwhile, I will be using the computer mouse to use chat. Thank you for the quick reply.

**Comment by basro** [comment]
Alternatively press Esc to defocus. The bug only happens when you defocus with tab.

**Comment by basro** [comment]
This bug has been fixed.
