### ISSUE TITLE
Irritating chat behavior

### ISSUE THREAD

**Issue by awareofdistractions** [haxball/haxball-issues#189]
Chat very rarely show newest messages.
In most cases users are constantly forced to scroll down to be able to see them.
It looks like random behavior.

**Comment by basro** [comment]
It works fine in the browsers I've tested it on, may I ask which browser and OS you are using?

There's a feature I implemented which will disable the scrolling to the bottom when a new message arrives if your mouse is hovering over the chat and it wasn't already scrolled to the bottom. This is there so that you can read old log messages in peace even if people are still chatting.

Does this behaviour also happen for you if you don't leave the mouse over the chat box?

**Comment by awareofdistractions** [comment]
I am using Solus Linux but other players on windows said they have the same problem.
I was testing Chrome, Vivaldi and Firefox, there was no difference.
`Does this behaviour also happen for you if you don't leave the mouse over the chat box?`
Yes but as I said it seems to happen randomly I can't find the cause(reproduce it).

**Comment by Simashax** [comment]
Agree with the awareofdistractions. I have the same problem with chat on Firefox on Windows 7, noticed it many times

**Comment by basro** [comment]
I've managed to reproduce the bug, but not if the mouse is not on top of the chat box.
@awareofdistractions are you absolutely certain that the bug happens even if you don't have the mouse hovering the chat box?

**Comment by awareofdistractions** [comment]
@basro Well now that I played on unmodified original version of haxball and without zoom so big that chat would take half of the screen I am not sure, you must be right and that bug can only appear with mouse hovering chat. Sorry for confusion.

**Comment by basro** [comment]
This is now fixed.
