### ISSUE TITLE
Can't join rooms

### ISSUE THREAD

**Issue by Davinho** [haxball/haxball-issues#203]
Hi, i have an issue on HTML haxball.

I have a macbook pro, i have no special program for html or anything but i can't join rooms. It always says connection closed. I used firefox and chrome, any ideas? (beside haxwin. It should just work with the normal site.)

**Comment by sonny124** [comment]
I have the same problem. 

Gif of what occurs when I try to join any html room: 
https://gyazo.com/9b7d28dc808e7b9ccb17537c46e29712

Using firefox, I've disabled all plug-ins, do not have adblock, and tried enabling and disabling reverse settings.

What is says in Inspect Element > Console on the "Connection Closed" screen: 
WebRTC interfaces with the “moz” prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.
modernizr-custom.js:3:5635
unreachable code after return statement
[Learn More]
js:64:1196

Is there a way to solve this problem? @basro

**Comment by basro** [comment]
That is weird..

@sonny124, does it also happen if you try to join a room hosted on that same pc?

**Comment by sonny124** [comment]
Yep, it happens when I try joining rooms hosted on the same mac (should've mentioned before, comp runs MacOS 10.11.4), using both Chrome and Firefox. Room doesn't show up in Public rooms list even when I choose the option to have it on the room list.

Error message in Chrome, maybe something here? @basro 
2 html5.haxball.com/:37 A parser-blocking, cross site (i.e. different eTLD+1) script, http://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=374327, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ ?c=V6dqi48g_kE:37

(My network connectivity seems to be just fine... internet speeds are 23.4mbps download and 0.81 upload)

Same error message in Console for Firefox:
WebRTC interfaces with the “moz” prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.
modernizr-custom.js:3:5635
unreachable code after return statement
[Learn More]
js:64:1196

**Comment by enes05** [comment]
![screenshot 2](https://user-images.githubusercontent.com/19493347/34518385-1e96e97e-f090-11e7-9313-9fdb9f7d0b52.png)
![screenshot 3](https://user-images.githubusercontent.com/19493347/34518391-24cc0aea-f090-11e7-8e31-5026d1e5ce16.png)

**Comment by basro** [comment]
@sonny124: 
Please try connecting and sending a message using this site: http://demos.kaazing.com/echo/
Tell me if it works.

**Comment by sonny124** [comment]
It works, all sent messages are echoed back.

**Comment by sonny124** [comment]
Any ideas? @basro

**Comment by basro** [comment]
@sonny124, sorry I forgot to reply.

It looks like the problem is the websocket connection to my server, but it's pretty strange since you seem to be able to establish and use websocket connections to other servers.

In any case, there's a fair chance that this problem will fix itself when I implement SSL. I hope to get that done this month.. I'll ping here when that's done and if it doesn't fix it we'll have to debug further.

Meanwhile, it would be helpful to know if this problem happens to you in different networks/routers. Eg, take your laptop to a different network and see if you get the same behaviour. It's a bit suspicious that both you and Davinho have this problem in mac os.

**Comment by sonny124** [comment]
@basro any solution? Unfortunately, I'm still getting the exact same issue.

**Comment by basro** [comment]
Nothing yet. I apologize, I haven't been able to put much time into it but it's the next thing on my todo list.

**Comment by someshit73** [comment]
I have the same problem too. I use W10. Do you have any solution? @basro

**Comment by basro** [comment]
I've just released an SSL enabled version of haxball.
@sonny124 @someshit73, sorry for the delay, I'd be interested in knowing if you still get the same problem.

**Comment by humpyy** [comment]
Players who weren't able to join my room before are able to now.

**Comment by basro** [comment]
That's great news @humpyy.
Hope it also fixes it for the other participants of this issue.
