### ISSUE TITLE
No option to save replay if host closes the room while you are recording

### ISSUE THREAD

**Issue by haxplayer** [haxball/haxball-issues#206]
If the host closes the room suddenly while I am recording, the room just closes without giving me the option to save the replay

**Comment by usmth** [comment]
What about an option in settings, where we can choose folder for saving replays?

Trigger: if room was closed - replay was automaticly saved in choosen folder.

**Comment by basro** [comment]
@usmth: it is not possible to do that with html5. I'll be handling this in the same way it was handled in the flash version which is by adding a download button to the disconnection dialog.

**Comment by cr0ndor** [comment]
I used to record every game I played on flash, and I would label it with a brief summary like 3-5 loss or something like that. I still record every game, but it's just a list of unidentifiable files now. Is there no way to trigger a popup window to file and name these files right after the game ends? Thanks.

**Comment by basro** [comment]
@cr0ndor: you can configure your browser to ask what name to give and where to save the files you download. Although this might be annoying since it will affect all the downloads you do with the browser. (I personally like it better like that though)

For chrome it's: Settings -> Advanced -> Downloads -> 'Ask where to save each file before downloading'
In firefox it's: Options -> General -> Downloads -> 'Always ask you where to save files'

**Comment by basro** [comment]
I've added a save replay button to the disconnect dialog, So you can now save replays even if you were disconnected.
