### ISSUE TITLE
Basro, wtf is this cheater? anybody knows this??

### ISSUE THREAD

**Issue by dvzq** [haxball/haxball-issues#2112]
[https://replay.thehax.pl/a1a3d23e-bb2a-4d9b-957d-4443fc27301f](url)

**Comment by guguxh** [comment]
isnt a cheat

**Comment by ChasmSolacer** [comment]
It looks like Zip "fake joined" many players named SGK with id 0, they are displayed as one player because they have the same id.
This is one of features of modded clients (some of which, free or paid, were advertised in the issues some time ago). They aren't real players, but just player objects controlled by nobody, as they aren't real players.
![image](https://github.com/haxball/haxball-issues/assets/46286197/0dc15b24-dc08-4daf-8f4d-a29b047e6959)

And the desynchronizations were probably caused by something else, you can ask Zip 🤐

**Comment by Rayit0** [comment]
Players called SGK are not players, they join player objects or "bots" to the room and can change the ping of "bots" or player objects, with a free client called node-haxball it is possible, the real SKG is the player with some ping. Their "bots" aren't playable the only use of these is to annoy, in fact you can also use the player objects or "bots" for playing chess or other things that you can imagine.

**Comment by ghost** [comment]
> Players called SGK are not players, they join player objects or "bots" to the room and can change the ping of "bots" or player objects, with a free client called node-haxball it is possible, the real SKG is the player with some ping. Their "bots" aren't playable the only use of these is to annoy, in fact you can also use the player objects or "bots" for playing chess or other things that you can imagine.

Bro, what a coincidence, another “Rayito” programmer in haxball.

**Comment by JuanRoDev** [comment]
> > Players called SGK are not players, they join player objects or "bots" to the room and can change the ping of "bots" or player objects, with a free client called node-haxball it is possible, the real SKG is the player with some ping. Their "bots" aren't playable the only use of these is to annoy, in fact you can also use the player objects or "bots" for playing chess or other things that you can imagine.
> 
> Bro, what a coincidence, another “Rayito” programmer in haxball.

Lol, what a coincidence, this is my secondary account, the real one is Raio0 :). I just realized that I wrote from my main account XD.
