### ISSUE TITLE
Still working on Haxball?

### ISSUE THREAD

**Issue by Kozlov98** [haxball/haxball-issues#214]
Every day we sent you our support, some Haxball communities are waiting for you to finish updating the first phase of the HTML5 version. We understand that you have a personal life and a job of insurance, but we would like to receive some small message of how things will be resolved within a few months, so that the administrators of the communities know how to act, since the game is losing many users

No encouragement of offenses, kozlov

**Comment by basro** [comment]
I am currently taking a break, but I will continue working on it in the future.

**Comment by haxballer** [comment]
@basro, truly? Poorly, you put it back again, leave us again. How much will we wait for next updates?  A year, two, three years? Not fair. You have given your appetites, you have hoped and the same again.

You would add a motif with saving replays after closing the host, and then took a break, because now it really irritates ... I hold for word that you will come back and you will continue this great project, because playing on HTML5 is in good condition, you can enjoy smooth haxball, in the end ... so many years of waiting, don't leave us, because we still believe in you.

Regards.
