### ISSUE TITLE
Coding IDE

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#267]
Is there any way to code on an IDE or something like that instead of coding on the browser's Console ?

**Comment by Raamyy** [comment]
No in my opinion,if we compare notepad with the browser's console, the Console is better as it slightly gives you some code completion but not always.

**Comment by saviola777** [comment]
Two options I have tested so far:

On **Chrome**, open the developer tools, then navigate to the "Sources" tab, then go to the "Filesystem" tab on the left panel, and add a folder from your local computer where you code is. There you also have a code editor with syntax highlighting etc., and when you want to load the code select everything (or just the part you want to execute), right click and pick "Evaluate in console".

On **Firefox**, I tried the extension [Custom Style Script](https://addons.mozilla.org/en-US/firefox/addon/custom-style-script/), here you can add custom Javascript automatically on page load, so you can for example create a GitHub repo for your code and then insert the link to your JS file so that it is automatically loaded when you open the headless hosting site – not as good for live development, but more comfortable for production use.

**Comment by Raamyy** [comment]
@saviola777  Thanks this really helped me :+1: 
But i found NotePad++ is the best choice right now, So if you don't know it you should try :smile:
