### ISSUE TITLE
Haxball Ranked Systeem

### ISSUE THREAD

**Issue by Phantom831** [haxball/haxball-issues#279]
http://fm-haxball.co.uk/community/viewtopic.php?f=188&t=7709&view=unread#unread

Welcome to our FM Community, 

You probably already heard of it. I want you to check out how many people really want this ranked games.
Check it out basro, Gimme as much info as you can about it.

Thanks

**Comment by basro** [comment]
> This thread is created as a result of a discussion with Basro. He wants to know how many people would be interested in this idea

I don't remember talking with anyone about this topic recently. He either spoke with someone impersonating me or is lying about it for some reason.

I don't have any near plans of implementing something like this.

**Comment by Stopbeinguseless** [comment]
Ok well can you actually give us some insight for once on what you plan on implementing? other than the html update what have you actually done for this game in 8 years of coding it? the game is at a point now where it desperatly needs revival updates because it's close to dying, maybe you should start getting more involved with the remaining loyal communitys you actually have left and take some of their ideas on board before it's too late.

**Comment by basro** [comment]
I don't have a strict plan, and I don't like your attitude either.

The user socrates from that thread saved me time. He pretty much mirrored what I'm thinking, read his comments. (up to this [post](http://fm-haxball.co.uk/community/viewtopic.php?f=188&t=7709&start=20#p72283), anything after that I've not read)

**Comment by Stopbeinguseless** [comment]
Yeah i can tell you don't have a strict plan, you've done about 4 updates since 2010, why didn't you sell the game to some developers years ago? there's no way you didn't have offers, be honest.
