### ISSUE TITLE
Animated form

### ISSUE THREAD

**Issue by pygmalionhere** [haxball/haxball-issues#361]
Hi! help me please
How to do that form effect?
https://i.imgur.com/amA0POY.gif

**Comment by Leo-MapCreator** [comment]
You gotta use onGameTick and a variable, so every Tick you will have a different value for this variable, and inside the onGameTick you have if's, if var > x, you set the 1st uniform, if var > y, you set the 2nd uniform, if var > z, you set the 3rd uniform and set var = 0 again, you can use more than just 3 different uniforms, that means more than 3 ifs, but the last if gotta reset the var to 0

**Comment by basro** [comment]
@pygmalionhere this probably being done using the headless host api.

@Leo-MapCreator: changing the team colors once per tick is quite definitely a bad idea. I do not recommend animating the team colors at all since it causes some cached images to be rebuild each time they change, old computers might have trouble keeping up with that. But if you choose to animate you should consider rate limiting so that it's not 60 changes per second, 10 per second would be reasonable.

**Comment by Leo-MapCreator** [comment]
Care to explain how to do that?

**Comment by basro** [comment]
Probably with the setInterval function https://www.w3schools.com/jsref/met_win_setinterval.asp

**Comment by Leo-MapCreator** [comment]
Thx
