### ISSUE TITLE
Little issues (windows xp)

### ISSUE THREAD

**Issue by eimattz** [haxball/haxball-issues#395]
When i create a server (windows xp) i cant move a player and settings, pick, link, leave and rec dont do nothing and the admin menu (Kick,ban,etc) dont appear

**Comment by basro** [comment]
Windows XP is no longer supported by most browsers, in particular chrome dropped support long ago and the last version of chrome that works for windows has those bugs.

I recommend you try with firefox since the last version that supported XP is more modern (version 52), I think it doesn't have these bugs.
