### ISSUE TITLE
Can't join some rooms. "Disconnected: Failed"

### ISSUE THREAD

**Issue by Rois11** [haxball/haxball-issues#416]
When I try to join some rooms it always shows this: https://gfycat.com/DenseMiserableFeline
So I've tried everything I found, even changing VPN (wich worked but I had 300+ ping so I couldn't play)

Any ideas?

**Comment by qLaur98** [comment]
Same happens to and at me .. https://imgur.com/a/yDWur6H ( mda bug..)

**Comment by Leo-MapCreator** [comment]
Happens a lot with me

**Comment by basro** [comment]
This is usually a problem with the router, unfortunately so far I've yet to find a router that had this problem and could be fixed by changing a setting in it so the only way to fix it is probably to change the router.

The reason why VPN works is that it effectively bypasses the router's problematic NAT.
