### ISSUE TITLE
Hosting 3 rooms

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#430]
When hosting 3 rooms only 2 are shown on room list. fix pls :d

**Comment by Leo-MapCreator** [comment]
Public: false ?

**Comment by basro** [comment]
There's a limit of 2 rooms per ip.

**Comment by olegmisar** [comment]
@basro could you increase limit of rooms per IP to 4-6? One machine can host 6 and more rooms without problems. If I want to host more than 2 rooms I have to use proxy or vpn what makes higher ping. If you have made limit against spammers it makes no sense because they can change IP. So, this limit is obstacle for good room hosts, not bad ones.

**Comment by Wolf72** [comment]
@basro Please increase limit to 4 T_T I am hosting 4 rooms and 2 rooms are almost always empty because of visibility. And players keep asking me why is room always down but it isn't. 

Also could you maybe add redirect? When room is full player is redirected to room that was set by host when creating.

**Comment by Leo-MapCreator** [comment]
I agree if it was upgrade to 3, i think 4 and so on is kinda much
