### ISSUE TITLE
Shoot input doesn't work when pressing Left+Bottom inputs

### ISSUE THREAD

**Issue by Gorgolet** [haxball/haxball-issues#462]
Hello, 

I notice with my colleagues that the shooting does not work when we move in "diagonal down left".That is when we keep moving down and left, we can no longer shoot.

I only notice this problem in this direction.

I do not find this problem in the lists of all issues, is it a problem already encountered?

Thanks in advance,

_Sorry about my english._

**Comment by olegmisar** [comment]
It's probably your keyboard problem (I am 99% sure). Number of wires which connect keys and computer is less than number of keys, so some keys use the same wire. It makes keyboards cheaper. Solutions:

- buy new keyboard which use separate wires for all(or almost all) keys
- use another keys to control your player. I believe you use arrows + space. You can use "x" instead of space.

**Comment by Gorgolet** [comment]
Hello olegmisar,

Thank you for your reply. We changed our key binds and everything works properly now.

Thank 👍
