### ISSUE TITLE
3 functions roomOnPlayerChat

### ISSUE THREAD

**Issue by tatqq** [haxball/haxball-issues#496]
Hello,
I would like the three functions to work, but only the one I will be the last to work (in this case setplayeraadmin).
Please help me :)

> room.onPlayerChat = function(player, message) {
>    if (message == "p"); {
>    room.pauseGame("true");
>    }
> }
> 
> room.onPlayerChat = function(player, message) {
>    if (message == "up"); {
>    room.pauseGame("false");
>    }
> }
> room.onPlayerChat = function(player, message) {
>    if (message == "xxxx"); {
>    room.setPlayerAdmin(player.id, true);
>    }
> }

**Comment by zikolo** [comment]
Don't pass string values. These functions take boolean values as its parameter. So not `"false"` but `false`. `"true"` will work in this case, because all non-empty strings evaluate to  `true` in javascript.

**Comment by saviola777** [comment]
If it's just your own code you can either combine the code into one function, or add a fourth function which calls all others. If you want something more flexible you can look at an [EventTrapper](https://github.com/morko/haxroomie-EventTrapper), which can collect several functions in the background instead of replacing the last.
