### ISSUE TITLE
Ip player object

### ISSUE THREAD

**Issue by xfermens** [haxball/haxball-issues#523]
please, add to player object  IP addres for learn fake player or not

**Comment by teisseire117** [comment]
If by fake player you mean players that take someone else username to fake his identity, then IP won't matter since it often changes.
What you can do tho is set up a !register command, so a player can set up a password, and in case someone else use his username, he would need to know the password to use chat/play/get stats updated(depending what you decide).
Also, I think there're too many risks that malicious hosts just steal people's IP to DDoS them when he's not happy, or during events, etc. If there were a real utility it would be okay but I don't think there is.

**Comment by xfermens** [comment]
idiot...

**Comment by xfermens** [comment]
The game developer, can you already start working?

**Comment by basro** [comment]
You can now identify players by using the auth property.
