### ISSUE TITLE
make room.kickplayer sends back an UID

### ISSUE THREAD

**Issue by teisseire117** [haxball/haxball-issues#541]
Hi,

I have a room, where if an 'unknown' admin bans a player, room.clearBans(); is called. To prevent abuses(got many).
Problem is, if I ban someone, he'll get banned. But if an unknown admin ban someone, everyone is unbanned.
I think it'll be useful to many people if you could make room.kickPlayer sends back an UID, which can be used in room.clearBans(ID); so we can ban a selected player through his ID.
That would help a lot.

Also I know it has been requested, and it's in my opinion the best feature that could happen, it's to add 'toPlayer' for room.sendChat(message, toPlayer);
It would be soo usefu. Add private message system, make the chat less spammed by the bot etc.

Anyway, thanks :D

**Comment by basro** [comment]
These two features have already been implemented some time ago but are yet to be released in the next update.

**Comment by evi1a** [comment]
Great news, but why did u chose to not release partial updates, if I may ask?
Because I think those features are essential and needed for a long time now.

**Comment by basro** [comment]
They are backwards incompatible changes and all rooms will have to be closed when the update happens, so I want to bundle more things in it.

**Comment by evi1a** [comment]
I see, so since you haven't released it yet I would like to make a suggestion with another simple thing that can be added/improved.

So for example, to get current/new data of a specific player we need to fetch whole list of players and filter it by id every time. There are two things that could improve the situation, one is adding `room.getPlayer(id)` and the other is using getters for every property, so you can directly access its value and it's up-to-date everytime.

Like in this example:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/get

**Comment by basro** [comment]
The two features are now released.
