### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#558]
Hello @basro Can you explain difference between id and auth variable? I cant understand it.

**Comment by dixtel** [comment]
Thanks for replay, Do you know how auth might be calculated, its is based on ip?

**Comment by AnddyAnddy** [comment]
No idea, only basro know

**Comment by basro** [comment]
Auth is randomly generated, it's not based on ip. Users can change their auth id anytime they want, but what they can't do is fake other player's auth id's (thanks to the magic of cryptography).

To clear some confusion: Auth allows you to tell if a player is actually who he claims to be, but it doesn't prevent two players controlled by the same person to have different auth since generating a new auth is trivial. This means auth is good for automatically authenticating admins or logging in users in your room, but it's not useful for combating spammers.

On the other hand there's also the "conn" property that is based on the player ip, you can use that for combating spam if that is your goal.

**Comment by Leo-MapCreator** [comment]
To clarify all:
ID - is the id of the player when he joins the room, changes everytime he joins the room
Auth - is the ''id'' of the player when he joins the room, its the same everytime he joins the room
Conn - is the "IP" of the player when he joins, doenst change when he joins the room and two accounts can have the same Conn

Is this right @basro ?

**Comment by basro** [comment]
Yes that is correct, except the Auth is not necesarily the same every time, the player can choose to change it at any moment.

**Comment by Leo-MapCreator** [comment]
How to change it?

**Comment by basro** [comment]
Deleting the key stored in local storage will change it. You can also change it from https://www.haxball.com/playerauth (although that ui requires that you already had a valid key previously generated)

**Comment by Wolf72** [comment]
> Deleting the key stored in local storage will change it. You can also change it from https://www.haxball.com/playerauth (although that ui requires that you already had a valid key previously generated)

well no need to tell them here that -.- xD
anyway clearBan should've been clearBan(conn) not clearBan(id)... :(

**Comment by listemanuel95** [comment]
Also player A can give player B their private key so that player B can play under player A's identity if they wanted to "cheat" the system.

**Comment by listemanuel95** [comment]
You can generate new keys by changing browsers or deleting the browser's cache (always using the https://haxball.com/playerauth UI).
You can also change your key by providing another VALID private key (your key will become the one you provided).

**Comment by basro** [comment]
Also note that you don't need to enter the /playerauth page for an ID to be generated, haxball will also generate one if it doesn't find one, so all players will get one generated by default.

**Comment by evi1a** [comment]
this is some next level shit :100:
