### ISSUE TITLE
Is it possible to trick game for extra FPS ?

### ISSUE THREAD

**Issue by Mirac35** [haxball/haxball-issues#566]
Haxball catchs your monitor's refresh rate and locks the game fps exacly same value. I've tried this game on many different monitors with many different tricks/tweaks. Game doesnt give f*** whats your G.Refresh Rate. You can trick windows by setting your refresh rate to 60 (or more) and g.refresh rate 120(or more) but not haxball (keep reading developers). In this way you can see in options you are using (fake) 120 HZ but game only gives you exact same fps what your refresh rate at. Thats the breakpoint for me. I didnt manage go past from here. Like i've said i can trick windows but not haxball. Any chance basro can remove vsync setting and add spesific fps locks more than 30 ? Settings will look like this on Settings>Video>FPS Limit: 30>60>(72?)75>86>90>110>120>144 and current setting No Fps Limit (reccomended). Adding this options may help some people who is suffering with input lag. Extrapolation is nice also but its like tricking windows with fake refresh rate :) I'm currently using 75 hz on 60 hz default monitor and i can feel the difference on controls. Please add more fps locks settings guys. 
Thanks for reading and i hope this helps for getting new ideas for developers.

**Comment by basro** [comment]
There's nothing I can do about this. Obviously I'd make a vsync setting if I could, but that is not something that the HTML5 api allows.
Web browsers render using vsync, making HaxBall render more frames would just be wasteful since those extra frames would never reach your computer screen.

The No FPS limit option means that there's no limit on HaxBall's side, meaning that if you manage to convince the browser to render 1000 frames per second, HaxBall will also render 1000 per second.
