### ISSUE TITLE
Modifying the chat display

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#709]
It's a suggestion.
As an illustration: 
https://gyazo.com/9f878fb2ea26c3ed03af70b37f429167
Don't pay attention to the alignements, it's made in 5 mins on paint.

So the purpose would be to separate the 3 sources of messages instead of having all these in only one chat window.
The illustration shows by itself, i'll not write 900 lines to explain why it would be better :p

**Comment by subxqns** [comment]
That looks awful and also chat timeline would lost with this design. But text-color changing ability in onPlayerChat would make it easier to highlights some messages, even when they're not sent by the host (e.g I have a teamchat command and would be a really good thing to highlight on red or blue those messages instead of showing [TEAM] at the beggining)

**Comment by AnddyAnddy** [comment]
The purpose of this suggestion is not to have a better view through the chat

It is meant to giving the choice  -- mainly to the headless -- to have a better display format.

For example, it would allow stuff like drawing tables of best scorers, assisters... 

Maybe by pushing farther this idea, the headless could contrôl a part of the html of the player, this means that a specific zone would be allowed to be changed to draw whatever we want with obviously some limits in term of size.

You need the best scorers ? Don't pay attention to the format, put a sql table into the html player that asked for the query and that's all

The image i've put was only the illustration of my idea, it can grantly be improved to a smooth thing

**Comment by Leo-MapCreator** [comment]
I like the idea
