### ISSUE TITLE
Flash working, HTML5 not

### ISSUE THREAD

**Issue by bartakabstina** [haxball/haxball-issues#753]
I have an infamous problem where when I try to join any room, I can't and I get the failed message. However, recently I've wanted to play some flash like in the old days, and weirdly though, Flash worked, but HTML5 didn't. Could you try and add a button that enables us to choose would we like to use HTML5 or Flash connecting?

**Comment by basro** [comment]
> Could you try and add a button that enables us to choose would we like to use HTML5 or Flash connecting?

Unfortunately that's not possible for me to do.

If flash works then html5 should almost always also work since they use more or less the same technique to establish a connection, have you tried using a different browser? (if you use chrome try with firefox, and if you use firefox try with chrome)

Also, keep in mind that sometimes you will fail to connect to rooms depending on who is the host, make sure to test html5 and flash connecting to the same person if possible.

**Comment by bartakabstina** [comment]
Thanks basro, you're the best.
