### ISSUE TITLE
Alright you cant remove Extrapolation. BUT -

### ISSUE THREAD

**Issue by Jacob-1998** [haxball/haxball-issues#773]
You could change the limit. There is absolutely no need for more than 50 extrapolation to fix whatever Input Delay problems a small minority of players have.

Putting the limit as 50 instead of 200 will fix the problem of competitive players using crazy numbers above 50 to get an advantage over other players, at the expense of their shakiness. This will fix the problem EVERYONE has to deal with (at least in EU Haxball).

They prefer to just win rather than have a fun smooth game, and for the rest of us it sucks because we have to join them and deal with shakiness or get beat by them.

If you want proof about top players using crazy numbers like 80 or 115 etc.. I can give you that.

**Comment by AnddyAnddy** [comment]
Preventing other players to play better is totally egoistic, yes it's unfair and it always been, players with 15 ping will have more potentiel to play better than players with 120 ping, should we also remove the ping ?

I feel a difference between 0, 20, 40, 60, 80, 100, 120+ extrapolation, why would players make their game lag if it's not to have better feelings ?

**Comment by Jacob-1998** [comment]
Because they are at a big advantage over other players seeing the game much earlier.

People with high extrapolation are playing in a different world/dimension to me where I look like an elephant because I'm seeing everything late compared to them. Its like the aim-bot cheat but for Haxball.

Why do you think most top players are using 80+ or 100+ extrapolation? Nobody wants a shaky game or has 'better feelings' like this. Its annoying, but they know its the only way to compete now.

2 options, deal with insane shakiness or deal with being slower than everybody else.

Anybody can see is a terrible situation to put players into, and this is not what basro intended to happen when he created extrapolation. It was for players to fix small input delay problems, NOT for players to get 'better feelings' by abusing extrapolation as a cheat when they don't need it for input delay problems.

Nobody with input delay problems needs more than 50, so thats where it should stop. It won't fix the issue 100% because these players will still be using 50 extrapolation to be at an advantage, but that is MUCH better than playing against /extrapolation 115 type numbers.

**Comment by Jacob-1998** [comment]
Its exactly like steroids in sports. It gives you big advantage, but there are negative side effects to using them.

Maybe your happy using steroids, but most people don't like the side effects and would rather not use it.

This is why steroids are banned in sports. Its not fair to force everybody to use them in order to compete, because without steroids vs steroids is extremely unfair, and its also not fair to force people to deal with steroid side effects.

Nobody using steroids is the fair and logical solution, which is what I'm suggesting.

**Comment by kojo953** [comment]
Players with high extrapolation dont have advantage over players with low extrapolation. With extrapolation u dont see the ball earlier, for example when two players will do rocket shot u see earlier ball with low extrapolation than high. With 120+ extrapolation u wont even see the shot, so how can it be an advantage?. Extrapolation just makes this game playable, and thats it. If u put high extrapolation its way harder to clear passes, to save shot, because everything is shaking

"If you want proof about top players using crazy numbers like 80 or 115 etc.. I can give you that."
U think that top players are on top bcs they are using high extrapolation? If u remove extrapolation they still will be on top.

**Comment by Jacob-1998** [comment]
Extrapolation predicts the future, you only get distortion when the original prediction doesn't come true. When the ball is kicked and you see there is nobody around to intercept it, you know 100% where the ball is going, and you see where the ball goes 115msec early instead of 50msec, is a big advantage to adjust your positioning with this early information.

Look at these quotes, they are not wanting to fix input delay, they want as maximum extrapolation they can possibly get while still being able to deal with the shakiness, because they know its massive cheat advantage to do skills easier:

https://i.imgur.com/ySdQbyi.png
https://i.imgur.com/6P2uAhR.png
https://i.imgur.com/Vl7LGKG.png
https://i.imgur.com/Zqy5F0q.png

So now the skill to be pro in Haxball is knowing how to deal with shakiness? This is what creates a good player, not only Haxball skills and intelligence, but learning how to handle a shaky game to benefit from crazy extrapolation? Its wrong and unfair on everybody else who doesn't want to deal with this shit. We are put in a disadvantage against these players. NOBODY needs more than 50msec to fix input delay, more than this is just ridiculous numbers to abuse extrapolation as a cheat like those quotes show, and like most people using extrapolation are doing it for.

And before you say it, of course top players will still be the best and bad players the worst blablabla.. Its irrelevant. The same level players against each other, the one who can handle and use higher extrapolation is in big advantage.

**Comment by kingjasko** [comment]
Just remove the graphical update, then we won't need to abuse extrapolation for the game to be playable... Nowadays people use 2.5x zoom so they feel less extrapolation lags and to feel "faster". While before the update it was mostly fine for everyone and zooming in would be similar to flash, it would become a bit blurrier, but no major problem apart from that... The resolution scaling doesn't do shit as well.

**Comment by Jacob-1998** [comment]
Yes that would work too. Remove the need for extrapolation, then take it off so players cant abuse it as a cheat to play with advantages.

And if you cant remove extrapolation because of hackers like you said in previous topic, make the extrapolation limit 1 after you removed the graphics update that causes small input delay (which still doesn't need more than 50 extra max to fix), problem solved. No input delay problems, no extrapolation cheat advantages.

**Comment by Mirac35** [comment]
Even him down the value to 50 it would be still accessable via injecting custom game-min.js.

**Comment by AnddyAnddy** [comment]
https://thehax.pl/forum/powtorki.php?nagranie=59670fa0f6c084b30087a13c6097b04d

On the first part i'm playing with 90 extrap
On the second part i'm playing with 0 extrap

Such a pleasure to shoot the ball at the exact moment I press x, don't you think ?

**Comment by Jacob-1998** [comment]
You have way better control and skill with 90 extrapolation yes. This is because you are seeing where the ball goes earlier, its giving you more skill like I said extrapolation would. If you have input delay problems, then its not more than 50msec, probably less. Any extrapolation number past that is just for you to get a skill boost like you demonstrated, because you are not skilled enough naturally to do nice rockets without cheats.

Which is why you said you would put more extrapolation if you could, even though right now your playing on 70 you already are shooting when you press x, its not about it being accurate to match your input delay, its about having as much extrapolation as you can handle for you to cheat yourself being more skilful. Really unfair to everybody else who doesn’t want to play with a crap shaky game just to be in an even and fair game against you.

What you showed just proved the unfairness of this cheat extrapolation, where players are in another dimension ahead of everybody else. Extrapolation wasn't meant to be a cheat, basro even said if he knew it would be used like this he would've never put extrapolation in the game. Thats why the limit should be 50 so that players who have input delay can fix that, and it ends there, no extreme extrapolation cheaters.

**Comment by kingjasko** [comment]
Well, I wouldn't call it a cheat, but it can certainly make anyone play better by fooling your brain to think faster and ahead of time in some situations, just needs time to get used to the lags and to start anticipating more things at once. Fact is, it's sacrificing the beauty and smoothness of the game for ingame advantage. But for me the unfair factor is that someone can run it fairly smoothly at high numbers, while others can't. Another problem is that randomly, from day to day, from room to room there are different feelings, it's never consistently good or consistently bad and I think that's only up to extrapolation. For a game this simplistic, having so many complications really drives me crazy.

IMO, this ruined competitive haxball, it changed the way people play (in a bad way), it made gameplay worse and a lot of the FM community feels demotivated and unwilling to put in as much time as before into playing this game, because it got flooded by people willing to tryhard enough to make themselves potentially better by playing in a certain (cancer) way, which extrapolation allows and in a way also promotes...

**Comment by timo212** [comment]
extrapolation is a shit basro please delete it

**Comment by Mirac35** [comment]
> extrapolation is a shit basro please delete it

nice problem solving abilities you got there

**Comment by Jacob-1998** [comment]
Well basro?

**Comment by meteus** [comment]
stop crying

**Comment by kingjasko** [comment]
> 
> 
> stop crying

we gotta face it, the game is in a terrible state, we only want what's best for the game and it's players, else it won't take long before no one plays it anymore

**Comment by Jacob-1998** [comment]
I would say 70% of the competitive community has already disappeared and won't come back. These are Haxball's most active and self-sustaining players. Please set the limit to 50 at the very least, we don't need 200 extrapolation its ridiculous.

**Comment by Mirac35** [comment]
> I would say 70% of the competitive community has already disappeared and won't come back. These are Haxball's most active and self-sustaining players. Please set the limit to 50 at the very least, we don't need 200 extrapolation its ridiculous.

mate even he limit the extrapolation to 50 its easily changeable.

**Comment by Jacob-1998** [comment]
> mate even he limit the extrapolation to 50 its easily changeable.

What? The limit right now is 200, he put that number as the max limit, so why couldn't he change that number to something else, and it would work the same way as the 200 limit works at the moment?

**Comment by Mirac35** [comment]
found this line in game-min.js : 
"this.cd = this.tc * (-200 > a ? -200 : 200 < a ? 200 : a)" then;
make 200's 1200
go to this line:
"case "extrapolation":
                    2 == a.length ? (d = K.parseInt(a[1]), null != d && -200 <= d && 200 >"
and make those 200's to 1200. and save then somehow inject your customized game-min.js to the game. there u go. u can type /extrapolation 1200 or even -1200 :) for more weirdness u can search for ".cd" in your game-min.js and play with the some values.

**Comment by basro** [comment]
I don't want instructions of how to modify the game in here.

The next update is going to set the limit to 50.

**Comment by basro** [comment]
I'm sorry but I'm reverting this decision, the negative reception was way stronger than I anticipated. With a reception that negative it'd not take long before people are sharing ways on how to bypass the limit.

As I expected, the only way change this is with a time machine.

**Comment by espierre31** [comment]
I think the limit has been exceeded. should be 100 instead of 200. This is because more powerful computers are advantageous. With 144 Hz monitor, the response rate of the 60 Hz monitor is not one. "extrapolation " 50 was very badly welcomed, they were right. But the 200 is too much. Especially in international matches, when the ping height is taken into consideration,  "extrapolation " is the superiority.

**Comment by Wiaz123** [comment]
+1 Pierre

**Comment by JC7shayki** [comment]
+1 @espierre31 you are very right.

**Comment by polackangry** [comment]
And in which game better computer and monitor does not give you an advantage? We should introduce communism and make everyone playing on shit conditions in a carton under the bridge.

All this crying is ridiculous, "lets make it difficult to play for everyone because we can not reach a certain level", pathetic.

**Comment by Norbyk44** [comment]
+1

**Comment by hostwarrior** [comment]
@espierre31 That would be a pretty nice solution to increase "gameplay equality" if we take into account the victimization of laptop and low hertz monitor users. Support that idea!

**Comment by kingjasko** [comment]
It's interesting to say the least. basro was for the longest time against the fact that extrapolation offers an advantage if you're willing to sacrifice game's smoothness (whatever that is in haxball) and now decides to contradict himself and limit it after weeks of feedback and comments from myself and others, but a few guys complain about the limit and it's back to how it was?

Well, anyways... I don't think extrapolation should exist, it was just the cheapest and easiest way to "fix" input lag, which was brought in by the graphical update of resolution scaling, which was before similar to how flash was - blurry when zooming in and it worked just fine in terms of game performance.

Instead of going forward and having a smooth, lag-free gameplay where everyone can have fun and enjoy the game and the competitive nature of it, the community is now once again divided by something stupid, because one incompetent, unambitious (sorry basro, but it's true) developer can't make up his mind...

And I repeat, it's a 2D game that should be working on any pc/laptop, heck I can even make it "work" on my phone, so why is it so hard to make it work normal for everyone? Why do we need something so random and unstable as extrapolation in the game in the first place?

Anyway, I'm wasting my time since nothing will ever change in this game.
