### ISSUE TITLE
Is basro a stubborn bigot ? 

### ISSUE THREAD

**Issue by Mirac35** [haxball/haxball-issues#800]
Or a classy gentleman ? Title is joke but really i don't understand why game doesn't get new features. We want to know more about this. Have you ever considered about user/player revievs ? Just add a random/desired/inspire idea feature and let us try it on haxball.com/playbeta and observe our revievs about it :) . Do you think the game's current state is exactly how you are expected back in 2010 ? 
On my first gameplay, i had this feeling; "wow, this game will be so popular in no time. maybe e-sports tournaments or something like that coming after **big leap**" but in my opinion, that big leap never came up. And we're still dealing with huge input delay with extrapolation 0 nowadays. Aaaaaaaaand i just found how to inject our old fixed(!) hacks like room blasting, increase room capacity etc.(u know the rest) that @Wrathen a.k.a HaxHack author created. (edit for players: pls dont even ask me how to)

**Comment by basro** [comment]
Sorry, I didn't realize I owed you something.
I made and maintained a free game that you seem to have enjoyed for about 8 years..
Oops my bad, I'm such a terrible person, sorry.

**Comment by pilaf** [comment]
@Mirac35 Did you ever consider that toxic commentary, acting entitled and personal attacks and aren't great ways to push for whatever it is you want?

Did you also consider that basro is in no way incompetent and that whatever issues the game may have may be due to bad/slow computers or warped player perception, and if there was something he could do to fix an issue he would?

And what's that bullshit about no new features? You only need take a look at the news section to see he implemented heaps of new features in the past year alone.

It's truly infuriating to see so many people like you who seem to value the game yet have nothing but disdain for its creator. How would that make you feel?

Try showing some sympathy for once.

**Comment by Mirac35** [comment]
shit... didn't want to be mean or toxic sorry for missunderstanding.

**Comment by AnddyAnddy** [comment]
9 years tbh xd

**Comment by Mirac35** [comment]
that's the spirit @basro  💃
