### ISSUE TITLE
RIP Haxball 2010-2019

### ISSUE THREAD

**Issue by Pedy2344** [haxball/haxball-issues#811]
So most people agree that the gameplay on flash was better, or at least if not  better than more fun. HTML is smoother but just doesn't feel the same for me and the ball feels extremely heavy. With 115 extrapolation i was able to have a great gaming experience, but then you came and changed the limit to 50 without even letting players adapt while the main EU league FM is still runn ing. Thanks for ruining the game basro.

https://fm-haxball.co.uk/community/viewtopic.php?f=188&t=8927&view=unread#unread

**Comment by TurboFalafel** [comment]
Few guys from fm =\= most people. "Great gaming experience with 115 extrapolation" - pls don't be funny, you guys were doing it only for gaining advantage over normal players, who want just play smooth game. Moving to HTML and decreasing extrapolation are changes that made haxball still playable, thank you Basro

**Comment by Pedy2344** [comment]
Your opinion is irrelevant because you are not at the level of the top players. If basro always listened to the average player than the game would  be even more shit.

About the gaining advantage you are completely delusional. Why do most people not play with high extrapolation then? Even lets say if they have low ping. Do  you know how fucking hard it is to play with 115 extrapolation? But its the only way for me not to feel too heavy. 

Thanks Basro, maybe idiot low iq's like Turbofalafel (what a name) can finally achieve something in this game when no1 is playing this game anymore.

**Comment by Pedy2344** [comment]
And BTW i think my technique was better in flash so again your just spouting nonsense in the form of bullshit and stop lying.

**Comment by TurboFalafel** [comment]
Wooow, someone became very nervous. Calm down bro, such skilled player as you will surely make it somewhere else, haxball is not the only existing game. I can't agree with your opinion about me, winning international cups puts me a little above average level.  Why do most people not play with high extrapolation? You answered your question 2 sentences later - it's fkin hard to play with such amount of extrapolation. Some players prefer enjoying the game rather than obsessive desire for victory ;)

**Comment by buraks52** [comment]
Are you serious, Basro? 50 extrapolation limit should be joke? I am having an InPut Lag problem and it is impossible for me to play with 50 extrapolation. I was overcoming the input lag problem by playing with 140 extrapolation. Extrapolation limit should be restored. I've been playing this game since 2011, but today Haxball is dead. RIP HAXBALL!

**Comment by basro** [comment]
The extrapolation change has been reverted.
