### ISSUE TITLE
Player radius

### ISSUE THREAD

**Issue by subxqns** [haxball/haxball-issues#834]
Is there any possibility to add the ability to change players' radius value in hbsfiles? and include the property in headless, so then we could change a specific player's radius

edit maybe we could set different values in hbs files the same way spawn points work

**Comment by basro** [comment]
Both of those things are possible since the last update, although you can't configure the radius per player.

I had forgotten to add the radius property to the docs though, look at the [PlayerPhysics](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#playerphysics) .hbs docs.

For headless simply use room.setPlayerDiscProperties(playerId, {radius: x} };

**Comment by subxqns** [comment]
Nice! I haven't tried it yet and since it wasn't in the docs I thought it was not possible ✌
