### ISSUE TITLE
Fix the pixel fake bug (Animation Frame Bug) [Evidence showed in gifs]

### ISSUE THREAD

**Issue by mob-hash** [haxball/haxball-issues#896]
https://gyazo.com/a0477d31cc9896dfde6da6dca4f1e17d

Even holding the x key still happening: https://gyazo.com/fd21288655fe58dc6aefe1ccb04531de

This is pixel fake bug. Or you can call it animation frame bug. Every higher extrapolation player using this technique to beat his opponents. 

Simply doing this while match is happening and your opponent seeing like same in the gif. They run to the ball to get it but guess what, the ball isn't kicked. It was animation frame bug. And 1-0. You are losing.

**How to produce this?**

Set your extrapolation around 90-200 (the more extra = more good example to see the bug)

 Kick the ball and a second before ball comes to you again, press x once. Be careful, you need to press kick button before ball arrives to your player, you need to be faster.

End of the issue, and message to @basro 

Basro, reproduce this thing and please fix it. We don't want other players using this method to win against people. Okay extrapolation is about "animation frames" I know, but I believe you can fix this issue. 

And you know what the best players in the world like Misaj, xSha, Isco. They all doing this shit. If you do this in the right time and right place, you easily get goal. And this is unfair situation. Which can be called as "cheating".

**Comment by Jacob-1998** [comment]
Well this is the exact problem with extrapolation. Its a lose-lose.

Either be slower than everybody else playing in a different time zone to them, or deal with this shitty shakiness.

Your better off using extrapolation for the time zone advantage even if you have the drawback of shakiness and fake x's like you showed, but its still annoying as hell. This is why extrapolation is the worst thing to happen to this game and is the downfall of Haxball.

Unfortunately even though basro was smart enough to realise this and put a 50 limit, he didn't have the backbone to carry it out because of 30 whiny kids who just complained without giving him any good reason to keep extrapolation.

Most league (and there are only two 4v4 leagues left in Haxball when there used to be loads) players hardly play friendlies anymore, we just turn up for matches twice a week. This game is such a mess considering what it used to be, hopefully basro wakes up and removes this toxic extrapolation again.

Basro would know most people welcomed the change if he actually saw what people were writing in the FM forum, and league players are the ones using the most extrapolation of all players.

**Comment by Wazarr94** [comment]
As basro stated, limitating the extrapolation to 50 was too late, since you can modify the game-min file in your computer to be able to be at 200 already.
It takes about 10 seconds to do, if you know how to modify your game min file.

**Comment by Jacob-1998** [comment]
Can basro not remove extrapolation by re-uploading Haxball to the internet, this time without the extrapolation?

**Comment by Wazarr94** [comment]
The game is unplayable if extrapolation doesn't exist, due to huge input lag

**Comment by Jacob-1998** [comment]
basro could also not add the graphics update that caused the input lag (for some people, I have 0) when he re-uploads Haxball to the internet, is it possible basro?

**Comment by Wazarr94** [comment]
HTML is what caused the extrapolation, flash handled it well, and then the fact it was html added a lot of input lag because of the browser, if I'm not mistaken.

**Comment by basro** [comment]
This is not a bug, it's doing exactly what it should.
