### ISSUE TITLE
Negative normal for planes

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#897]
Hello,

Small issue to understand why planes work like the way they do.

Why does the plane go the opposite x coordinate when you invert the normal ? It should be in the same position, just blocking the other side of the map. 
If (a, b) is a normal vector to a line, then (-a, -b) is another normal vector to the same line.

Is there something I missed ? 
Thanks

**Comment by basro** [comment]
When dist is 0 the plane boundary will be a line that goes through <0, 0>, the normal will define it's direction.

Planes collide with things on the negative side of the normal:

![hbplane](https://user-images.githubusercontent.com/1387293/64908119-209ac180-d6d2-11e9-963e-3b4e9e73f4e5.png)

In this case the normal is pointing up so everything under the plane is going to collide and get pushed up.

Dist will offset the plane in the direction of the normal. A negative dist will move the plane backwards along the normal.

Because the plane extends infinitely to the sides these two parameters are enough to define any plane.

**Comment by Wazarr94** [comment]
Ohhh I see, the explanation makes sense, although I don't like how it works.

Thanks 👍

**Comment by Wazarr94** [comment]
Also, just realized the way you describe it is the only way to make it so you can describe all planes, alright !
