### ISSUE TITLE
FPS Advantages/Disadvantages and Game resolution/zoom

### ISSUE THREAD

**Issue by yaitsmeyouknow** [haxball/haxball-issues#91]
The difference in the feel of the game with 60 fps vs 120/144 fps is HUGE. You feel MUCH slower/heavier with 60 fps. Players with 60 fps stand 0 chance vs someone with higher fps if the skill level is similar at all.

I was also wondering if you could please add an option to use the old dimensions of flash hax. I know there's a zoom but it's not really the same at all. After playing with the old resolution and default zoom level it had, there are many that prefer it that way. There's also some that prefer the new way, so I don't think adding an option to play between both of them would be bad, but instead be a great feature for the game.

**Comment by basro** [comment]
The internal game physics run at 60 fps.
In HaxBall html5 I've implemented interpolation between frames so that any framerate looks smooth, but I don't agree that a 60 fps player stands no chance against a higher framerate player. The advantage is minimal or non existent.

I'll add a restricted viewport size option soon.
